version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: musicdb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: musicuser
      MYSQL_PASSWORD: musicpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -prootpassword || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - music-network

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - music-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live || exit 1"]
    #   interval: 30s
    #   retries: 3
    #   start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 50M
    ports:
      - "8080:80"
    networks:
      - music-network

  app:
    build: .
    container_name: music-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "7070:7070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/musicdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: musicuser
      SPRING_DATASOURCE_PASSWORD: musicpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_PROFILES_ACTIVE: "dev"
      JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      JWT_EXPIRATION: "300000"
      SECURITY_ALLOWED_DOMAINS: "http://localhost:3000,http://127.0.0.1:3000"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET: "music"
      MINIO_PRESIGNED_EXPIRATION: "1800" # 30 minutos
    networks:
      - music-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7070/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  music-network:
    driver: bridge

volumes:
  mysql_data:
  minio-data:
